development:
  clients:
    default:
      database: crawler_development
      hosts:
        - localhost:27017
      options:
        user: 'dbadmin'
        password: '1234567890'
        roles:
          - 'dbOwner'
test:
  clients:
    default:
      database: crawler_test
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0
        user: 'dbadmin_tester'
        password: '1234567890'
        roles:
          - 'dbOwner'
